#!/bin/bash
clear
cd /home/dvmega
echo -e "\033[33m"
echo "###################################################"
echo "## DV-MEGA LTD GENESIS OLED SCREEN SAVER INSTALL ##"
echo "###################################################"
echo -e "\033[31m    YOUR SYSTEM MUST BE IN READWRITE MODE"
echo -e "if not the case, please press ctrl-c to stop"
echo -e "\033[33m    else press ENTER to start the process"
read -p ""
echo "---> Enable the read-write system disk"
sudo mount -o remount,rw / ; sudo mount -o remount,rw /boot
sleep 1
echo -e "---> Stopping MMDVMHost service\n"
sudo systemctl stop mmdvmhost.timer
sudo systemctl stop mmdvmhost
sleep 1
if [ ! -f /usr/local/bin/MMDVMHost.original ] ; then
  echo -e "---> Backing up existing MMDVMHost binary to MMDVMHost.original\n"
sudo cp /usr/local/bin/MMDVMHost /usr/local/bin/MMDVMHost.original
fi
sleep 1
echo " " 
echo "---> Download the DM-MEGA NODE Oled driver"
sudo git clone https://github.com/f5swb/dvmega_OLED.git
sleep 1
echo -e "---> Copy the DM-VEGA NODE Oled driver\n" 
sudo cp /home/dvmega/dvmega_OLED/MMDVMHost /usr/local/bin/MMDVMHost
sleep 1
#sudo chmod 777 /home/dvmega/dvmega_OLED/libArduiPi_OLED.so.1.0
#sudo cp /home/dvmega/dvmega_OLED/libArduiPi_OLED.so.1.0 /usr/local/lib/libArduiPi_OLED.so.1.0
#sleep 1
echo -e "---> Enable the read-only system disk\n"
sudo sync ; sudo sync ; sudo sync ; sudo mount -o remount,ro / ; sudo mount -o remount,ro /boot 
echo "---> Now restarting MMDVMHost service"
sudo systemctl start mmdvmhost
sleep 1
echo -e "---> Cleaning the repository files"
cd ..
sudo rm -r /home/dvmega
echo "---> The system is now updated"
sleep 1
echo -e "\033[31m"
echo -e "Remember that if you do a pistar-update & pistar-upgrade you will loose the DV-MEGA LTD screen saver !\n"
echo -e "\033[33mGood trafic with the GENESIS NODE\n"

